name: Simple Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

env:
  NODE_VERSION: '18'

jobs:
  # 简化的部署任务
  deploy:
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
    - name: Checkout代码
      uses: actions/checkout@v4

    - name: 部署到服务器
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          # 创建部署目录
          mkdir -p /opt/wechat-education
          cd /opt/wechat-education
          
          # 备份当前版本
          if [ -d "current" ]; then
            mv current backup-$(date +%Y%m%d-%H%M%S) 2>/dev/null || true
          fi
          
          # 克隆最新代码
          git clone https://github.com/${{ github.repository }}.git current
          cd current
          
          # 生成package-lock.json文件
          npm install
          cd backend && npm install && cd ..
          
          # 创建环境配置
          if [ -f .env.production ]; then
            cp .env.production .env
          else
            cat > .env << 'EOF'
          NODE_ENV=production
          MYSQL_ROOT_PASSWORD=secure_root_pass_2024
          MYSQL_DATABASE=wechat_education
          MYSQL_USER=appuser
          MYSQL_PASSWORD=secure_app_pass_2024
          MYSQL_PORT=3306
          REDIS_PORT=6379
          JWT_SECRET=your_very_secure_jwt_secret_key_change_this_in_production_2024
          BACKEND_PORT=3000
          NGINX_HTTP_PORT=80
          NGINX_HTTPS_PORT=443
          CORS_ORIGIN=*
          EOF
          fi
          
          # 停止旧服务
          docker-compose down 2>/dev/null || true
          
          # 构建并启动新服务
          docker-compose up -d --build
          
          # 等待服务启动
          echo "等待服务启动..."
          sleep 60
          
          # 健康检查
          max_attempts=10
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            if curl -f http://localhost/health 2>/dev/null; then
              echo "✅ 部署成功！服务正常运行"
              # 清理旧备份（保留最近3个）
              ls -t backup-* 2>/dev/null | tail -n +4 | xargs rm -rf 2>/dev/null || true
              exit 0
            else
              echo "尝试 $attempt/$max_attempts: 服务尚未就绪，等待10秒..."
              sleep 10
              attempt=$((attempt + 1))
            fi
          done
          
          echo "❌ 部署失败，服务健康检查未通过"
          echo "查看服务状态:"
          docker-compose ps
          echo "查看日志:"
          docker-compose logs --tail=50
          exit 1

  # 通知
  notify:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: 发送部署通知
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "✅ 部署成功！应用已更新到最新版本。"
          echo "🌐 访问地址: http://${{ secrets.SERVER_HOST }}"
          echo "📋 API健康检查: http://${{ secrets.SERVER_HOST }}/api/v1/health"
        else
          echo "❌ 部署失败！请检查日志并重试。"
        fi